### ISSUE TITLE
Cannot import RDC file in blender - 

### ISSUE THREAD

**Issue by fanatikmhd** [eliemichel/MapsModelsImporter#112]
All files is recent ones (MMI, RD, Blender...)
I try it, but something is wrong when i need to import. I think, theres something installed in your blenders what i dont have....

![problem](https://user-images.githubusercontent.com/75045847/100287335-bab3f600-2f74-11eb-9ada-d9d2fa900d4e.png)

[pumpa 3.zip](https://github.com/eliemichel/MapsModelsImporter/files/5599504/pumpa.3.zip)

**Comment by fpibbs** [comment]
Same error...

**Comment by camosquirrel** [comment]
Precisely the same error for me.

Blender 2.91.0
Map Models Importer release 0.3.3
RDC file from https://blog.exppad.com/public/webgl-renderdoc/gmaps/capture.rdc
(self captured RDC files give same error)
Win 10 Pro release 19042.630

**Comment by eliemichel** [comment]
HIi @fanatikmhd,
Your RDRC is valid:
![image](https://user-images.githubusercontent.com/5802849/100500349-a4bc5600-316b-11eb-9add-6b12b7e23366.png)

From your error screenshot it appears that the add-on cannot find `python.exe` that should be located at `C:/Programy/Blender 2.91/2.91/python/bin/python.exe` in your case. Can you tell if this file indeed exists? Or are you able to find it elsewhere?

**Comment by robogrow** [comment]
My python.exe is there. Still have same error as others.

**Comment by mdibenigno** [comment]
I have the same issue and can confirm python.exe exists in that folder.

**Comment by mpentek** [comment]
Hello,

I want to say that I have the same/similar issue, although the error messages are slightly different. The traceback consistently refers at the upper most level to line 54 in `operators.py`. Currently testing on 3 systems and asking a colleague to try it out as well. Here the errors on various systems when trying to import the `HongKong.rdc` sample model.

**System 1 info :** Win 10 (OS build 19042.630) + (RenderDoc v1.11) Blender 2.90.1 + Python 3.7.7 (within Blender)
[system_1_info.txt](https://github.com/eliemichel/MapsModelsImporter/files/5618002/system_1_info.txt)
```
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.space_data.system_bookmarks_active = 2
bpy.context.space_data.system_bookmarks_active = 3
Traceback (most recent call last):
  File "C:\Users\pmt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\pmt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 272, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "C:\Users\pmt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 50, in captureToFiles
    os.environ["PYTHONPATH"] += os.pathsep + os.path.abspath(getBinaryDir())
  File "C:\Users\pmt\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\utils.py", line 47, in getBinaryDir
    }[platform.system()][platform.architecture()[0]]
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\platform.py", line 1068, in system
    return uname().system
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\platform.py", line 956, in uname
    node = _node()
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\platform.py", line 759, in _node
    import socket
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\socket.py", line 52, in <module>
    import os, sys, io, selectors
ValueError: source code string cannot contain null bytes

location: <unknown location>:-1
```

**System 2 info :** Win 10 (OS build ...) + (RenderDoc v..) Blender ... + Python ... (within Blender)

```

```

**System 3 info :** Win 10 (OS build ...) + (RenderDoc v...) Blender ... + Python ... (within Blender)

```

```

**Comment by cr3you** [comment]
Same error here. On two independent machines with windows 10.
Fresh Blender install (v2.91.0) on both computers.
Tested on Pumpa.rdc and other examples.
Python.exe is in the c:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\ directory
![blenderMapsImportError](https://user-images.githubusercontent.com/73391409/100667724-2aeabf00-335b-11eb-86df-607e4d652699.png)

**Comment by fanatikmhd** [comment]
Hi, for my post @eliemichel - I have my Blender on disk "E", but yes, python is here. On C-drive, theres only W10... I try it in many ways, i cannot import rdc file into blender - but when you try it on your maschine (screen upper), i see that rdc file is good. So, problem is somewhere in importer. Is there an option, that MapsModelsImporter (MMI) is connected to your tree/subtree where you have your instalation? Like, i need to install Blender in same location (C:\Program Files.....)?

**Comment by Astrak** [comment]
No clue about the issue from me but as a quick workaround I've been able to make it work again with v0.2.2 for the add-on, v1.1 for renderdoc, and blender 2.83.1.

**Comment by mpentek** [comment]
Update: the very specific version requirements and recommendation for this plugin do work! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.3

**Comment by gembac** [comment]
I had the same error. Worked fine when I installed older versions: Blender 2.90.0 and RenderDoc v1.10

**Comment by eliemichel** [comment]
Okey I finally figured out: `sys.executable` used to indicate `blender.exe` until 2.90, and since 2.91 it points to `python.exe` so it totally broke the way we were looking for python. It should be fixed by [v0.3.4](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.4)!

**Comment by robogrow** [comment]
Thank you!

We would like to display proposed autonmous guideway on streets in 3D. aaaaaaaaaaaaais the RDC format documented somewhere so we can display it with some python cloud library?

http://turfrobots.us/media/ag1.mp4

**Comment by eliemichel** [comment]
The Python API for manipulating rdc files is available here: https://renderdoc.org/docs/python_api/index.html
But if I understand correctly your point what's wrong with sampling random points on the mesh once imported?

**Comment by robogrow** [comment]
Yes, I want to register the RDC point cloud to at least three gps(x,y,z) coordinates and then merge the point could with the guideway mesh(ie. stl) . In a perfect world we would like to use this interface as a real time monitoring control system and guideway traffic simulator. So that means updating many 3D overlay object (pods) at 30 FPS.

Also, I am responding to a smart vity RFP. I'd like to render city streets and display fog point cloud to reflect air pollution and greenhouse gases measured by IOT sensors. The more opaque the fog the higher the measure gas/particulate. Each gas will have a different color. This pilot also will have smart intersection, Noise source location, and multi-model traffic counts so it would be nice to render this on an actual 3D map of the city.

Would you be interested in this work if we get the contract?

Thanks for your support.

**Comment by robogrow** [comment]
Using renderdoc 1.11 & blender 2.91 still getting this error with new version 3.4

**Comment by robogrow** [comment]
Since I was getting the same missing file error with v3.4, I installed Blender v2.90 and am now getting a Invalid RDC capture file error for both v3.3 and v3.4.

The error instructions say to download a know good capture file to test. I can't find one can you point me to one?

**Comment by robogrow** [comment]
Sorry, I must have misstyped url for samples. I downloaded the Funkhaus.rdc sample file and got the same "invalid rdc capture file" error as previously noted using Blender 2.90 and v3.3 map model importer.
